# Aqui começa meu estudo Python e Jupyter
### Livro --> Python: guia prático do básico ao avançado

In [3]:
print("Olá mundo!")

Olá mundo!


In [4]:
import this

In [5]:
a = 77
b = 10
c = a + b
print ("Soma de a + b = ", c)

Soma de a + b =  87


<h1 style="color: lightblue">Capítulo 1</h1>
<p style="color: gray">Noções de instalação de bibliotecas, frameworks, IDE's, além de mostrar usos básicos do Jupyter Notebook (Jupyter = Julia + Python + R).</p>

In [7]:
a = 10

In [8]:
b = 20

In [9]:
c = a + b

In [10]:
print(c)

30


<h1 style="color: lightblue">Capítulo 2</h1>
<p style="color: gray"><b> Variáveis, tipos, estruturas e operações<b></p>
<p style="color: gray"> Plano de construção de algoritimos: <br>
    - Definir o problema <br>
    - Separar em partes <br>
    - Ordenar atividades <br>
    - Traduzir para códigos <br>
    - Obter solução do problema</p>

### Operações

In [11]:
#Soma
2 + 2

4

In [12]:
#Subtração
2 - 1

1

In [13]:
#Multiplicação
7 * 7

49

In [14]:
#Divisão
7/2

3.5

In [15]:
#Mõdulo ou resto da divisão
9%2

1

In [19]:
#Divisão com um / retorma um float
6/2

3.0

In [20]:
#Divisão com duas // retorna um int
6//2

3

### Função type

In [16]:
type(77)

int

In [17]:
type(1.618)

float

In [18]:
type("Aqui temos um texto")

str

### Conversão de números

In [21]:
float(3)

3.0

In [22]:
int(1.0)

1

In [23]:
int(1.618) #coletando apenas a parte inteira

1

### Transformações: hexadecimal e binário

In [24]:
hex(77) # para representar o inteiro 77 em hexadecimal

'0x4d'

In [25]:
hex(231)

'0xe7'

In [26]:
bin(77)

'0b1001101'

In [27]:
bin(231) # para representar o inteiro 231 em binário

'0b11100111'

### Funções para computação científica

In [29]:
# Retorna o valor absoluto (positivo)
abs(-8)

8

In [30]:
# Retorna o valor absoluto
abs(8)

8

In [31]:
# Retorna a potência qualquer de um número 
pow(2,8) # potência de 2 ^ 8 (dois elevado a 8)

256

In [32]:
# Retorna a potência
pow(5,100) #potência de 5 ^ 100

7888609052210118054117285652827862296732064351090230047702789306640625

In [33]:
# faz arredondamento de números
round(3.1415)

3

In [34]:
round(1.618)

2

In [35]:
# Arredondar com duas casas decimais
round(1.616,2)

1.62

### Diferença entre valor e variável

In [36]:
a = 77 # variável 'a' com valor atribuído 77

In [37]:
print(77) # imprime o valor 77

77


In [38]:
print(a) # imprime o valor da variável 'a'

77


### Declarando variáveis

In [39]:
# Atribuindo o valor 7 à vriável var_a
var_a = 7

In [40]:
# Imprimindo o valor da variável
var_a

7

In [42]:
# Imprimindo o valor da variável
print(var_a)

7


In [43]:
var_c = 20

In [44]:
type(var_c)

int

In [47]:
#variável do tipo float aloca um espaço de 4 bytes
#variável do tipo double aloca 8 bytes

In [48]:
var_d = 3.14

In [49]:
type(var_d)

float

In [50]:
var_e = 11.

In [51]:
type(var_e)

float

### Variável do tipo string

In [52]:
str_var_1 = 'A'

In [53]:
type(str_var_1)

str

In [54]:
str_var_2 = 'Python'

In [55]:
type(str_var_2)

str

In [56]:
str_var_3 = "Python uma excelente linguagem!"

In [57]:
type(str_var_3)

str

### Concatenando strings

In [58]:
nome1 = "Maria"

In [62]:
nome2 = " Renata"

In [63]:
total = nome1+nome2

In [64]:
total

'Maria Renata'

### Variável booleana

In [65]:
a = True #Obs: True deve iniciar com letra maiúscula

In [66]:
type(a)

bool

In [67]:
b = False # Obs: False deve iniciar com letra minúscula

In [68]:
type(b)

bool

### Declaração múltipla

In [69]:
disciplina1, disciplina2, disciplina3 = "Química", "Estatística", "Matemática"

In [70]:
disciplina1

'Química'

In [71]:
disciplina2

'Estatística'

In [72]:
disciplina3

'Matemática'

In [73]:
assunto1 = assunto2 = assunto3 = "Teoria da relatividade"

In [74]:
assunto1

'Teoria da relatividade'

In [75]:
assunto2

'Teoria da relatividade'

In [76]:
assunto3

'Teoria da relatividade'

In [77]:
idade, nome, vivo = 30, "Renata", True

In [78]:
idade

30

In [79]:
nome

'Renata'

In [80]:
vivo

True

### Erros comuns

In [82]:
7x = 50 #Mensagem de erro, pois o python não permite nomes de variáveis que iniciem com números

SyntaxError: invalid syntax (4243905531.py, line 1)

In [83]:
class = 3 # class é uma palavra reservada em python

SyntaxError: invalid syntax (1795098644.py, line 1)

### Operações com variáveis

In [84]:
var1 = 10

In [87]:
var2 = 3

In [88]:
var1+var2

13

In [89]:
var2-var1

-7

In [90]:
var1*var2

30

In [91]:
var2/var1

0.3

In [92]:
var2%var1 #resto da divisão var2/var1

3

In [94]:
#Obs: a indexação em Python começa por ZERO
#Em python usamos o [] para representar o índice de um objeto

In [95]:
varstr = 'Estudo'

In [96]:
varstr[0]

'E'

In [97]:
varstr[1]

's'

In [98]:
varstr[2]

't'

In [99]:
varstr[3]

'u'

In [100]:
varstr[4]

'd'

In [101]:
varstr[5]

'o'

In [102]:
#podemos buscar o indíce que contém determinado caracter(es)
varstr.find('t')

2

In [103]:
varstr.find('ud')

3

In [104]:
frase = 'Python é uma linguagem muito poderosa'

In [105]:
frase[2:]

'thon é uma linguagem muito poderosa'

In [106]:
frase[:12]

'Python é uma'

In [107]:
frase[-1]

'a'

In [115]:
frase[-9:-3]

' poder'

In [116]:
frase[::1] #retorna a string pulando 1 caracter

'Python é uma linguagem muito poderosa'

In [117]:
frase[::2] #retorna a string pulando 2 caracteres

'Pto  m igae ut oeoa'

In [118]:
frase[::3] #retorna a string pulando 3 caracteres

'Ph u namuoora'

In [119]:
frase[::-1] #retorna a strinf pulando 1 caracter

'asoredop otium megaugnil amu é nohtyP'

### Funções

In [120]:
texto = 'Python para análise Quant.'

In [121]:
texto.upper() #transforma texto para carateres maiúsculos

'PYTHON PARA ANÁLISE QUANT.'

In [122]:
texto.lower() #transforma texto para caracteres minúsculos

'python para análise quant.'

In [123]:
texto.split() #divide string por espaços em branco (padrão da função)

['Python', 'para', 'análise', 'Quant.']

In [124]:
texto.split('t') #divide string no elemneto esécificado 't'

['Py', 'hon para análise Quan', '.']

### Listas

In [125]:
lista_vazia = [] #cria lista vazia

In [126]:
lista_vazia2 = list() #tbm cria lista vazia

In [127]:
type(lista_vazia)

list

In [128]:
type(lista_vazia2)

list

In [129]:
#para criar listas utilizamos []
lista_nomes1 = ['Robson', 'Ricardo','Rafael','Renata']

In [133]:
lista_nomes2 = ['Robson, Ricardo, Rafael, Renata']

In [134]:
type(lista_nomes1)

list

In [135]:
type(lista_nomes2)

list

In [136]:
#função len() diz o tamanho da lista
len(lista_nomes1)

4

In [137]:
len(lista_nomes2)

1

In [138]:
lista_nomes1[0] #retorna o elemento index 0

'Robson'

In [139]:
lista_nomes2[0]

'Robson, Ricardo, Rafael, Renata'

In [143]:
lista_mista = ['elevador',77,3.14]

In [144]:
print(lista_mista)

['elevador', 77, 3.14]


In [145]:
print('Tamanho da lista = ', len(lista_mista))

Tamanho da lista =  3


In [146]:
lista_mista[0]

'elevador'

In [147]:
lista_mista[1]

77

In [148]:
lista_mista[2]

3.14

In [149]:
#Obs: erro index out of range tentativa de acesso e elemento fora do range

### Deletando elemento da lista

In [150]:
del lista_mista[1]

In [151]:
print(lista_mista)

['elevador', 3.14]


In [152]:
lista_mista2 = ['casa',77,3.14,'viagem',123,10,3,77]

In [153]:
lista_mista2

['casa', 77, 3.14, 'viagem', 123, 10, 3, 77]

In [154]:
lista_mista2.remove(3.14)

In [155]:
lista_mista2

['casa', 77, 'viagem', 123, 10, 3, 77]

In [157]:
lista_mista2.remove(77)

In [158]:
lista_mista2

['casa', 'viagem', 123, 10, 3, 77]

In [159]:
lista_mista2.remove(77)

In [160]:
lista_mista2

['casa', 'viagem', 123, 10, 3]

### Aninhamento de listas

In [161]:
#criar uma lista de listas
lista = [[11,22,33],[1,2,3,4],[100,200,300,400,500]]

In [162]:
lista

[[11, 22, 33], [1, 2, 3, 4], [100, 200, 300, 400, 500]]

In [164]:
type(lista)

list

In [165]:
len(lista)

3

In [166]:
lista[0]

[11, 22, 33]

In [167]:
type(lista[0])

list

### Fatiamento (slice)

In [168]:
lista

[[11, 22, 33], [1, 2, 3, 4], [100, 200, 300, 400, 500]]

In [169]:
lista[2][2] #da lista 3 pegue o elemento 3

300

In [170]:
lista[2][4] #da lista 3 pegue o elemento 5

500

### Juntando listas

In [171]:
lista1 = [1,2,3,4,5]

In [172]:
lista2 = [22,33,44,55,66,77]

In [173]:
sua_lista = lista1+lista2

In [174]:
sua_lista

[1, 2, 3, 4, 5, 22, 33, 44, 55, 66, 77]

### Outros fatiamentos

In [175]:
minha_lista = ['tio', 'mãe','pai','irmão','sobrinha']

In [176]:
#fatiando os 4 primeiros elementos da lista
minha_lista[0:4]

['tio', 'mãe', 'pai', 'irmão']

In [177]:
#fatiando os elementos 2 a 7 da lista
minha_lista[1:3]

['mãe', 'pai']

In [179]:
#Último elemento da lista
minha_lista[-1]

'sobrinha'

In [180]:
#Elementos de trás para frente da lista
minha_lista[::-1]

['sobrinha', 'irmão', 'pai', 'mãe', 'tio']

### verificar se um elemento está na lista

In [181]:
sua_lista

[1, 2, 3, 4, 5, 22, 33, 44, 55, 66, 77]

In [182]:
20 in sua_lista #avalia se 20 está na sua_lista

False

In [183]:
77 in sua_lista

True

In [184]:
sua_lista.append(121) #adiciona o elemento no fim da lista

In [185]:
sua_lista

[1, 2, 3, 4, 5, 22, 33, 44, 55, 66, 77, 121]

In [186]:
sua_lista.count(33) #conta quantas vezes o elemento aparece 

1

In [187]:
sua_lista.index(121) #saber o índice do elemento 

11

In [188]:
sua_lista.insert(6,101) # adiciona o elemento 101 na posição 7

In [189]:
sua_lista

[1, 2, 3, 4, 5, 22, 101, 33, 44, 55, 66, 77, 121]

In [190]:
sua_lista.sort() #ordena os elementos da lista

In [191]:
sua_lista

[1, 2, 3, 4, 5, 22, 33, 44, 55, 66, 77, 101, 121]

In [192]:
sua_lista.reverse() #inverte a ordem dos elementos

In [193]:
sua_lista

[121, 101, 77, 66, 55, 44, 33, 22, 5, 4, 3, 2, 1]

### cópia e criação de listas

In [194]:
#lista de números
numeros = [11,22,33,44,55]

In [195]:
#faz referenciação de numeros para novos
novos = numeros

In [196]:
#adiciona valores a lista 'novos'
novos.append(1)
novos.append(77)

In [197]:
#veja o que acontece
numeros

[11, 22, 33, 44, 55, 1, 77]

In [198]:
#cria nova variável com elementos de 'numeros'
numeros2 = numeros[:]

In [199]:
numeros2.append(57)

In [200]:
numeros

[11, 22, 33, 44, 55, 1, 77]

In [201]:
numeros2

[11, 22, 33, 44, 55, 1, 77, 57]

In [202]:
novos

[11, 22, 33, 44, 55, 1, 77]

In [203]:
#faz cópia dos elementos de 'numeros' para 'numeros3'
numeros3 = numeros.copy()

In [205]:
#faz cópia dos elementos de 'numeros' para 'numeros3'
numeros4 = list(numeros)

In [206]:
numeros3

[11, 22, 33, 44, 55, 1, 77]

In [207]:
numeros4

[11, 22, 33, 44, 55, 1, 77]

In [208]:
lis = [] #cria lista vazia

In [209]:
type(lis)

list

In [210]:
len(lis)

0

In [212]:
lis.append(1)

In [213]:
lis

[1]

### List comprehension

In [1]:
#Operações matemática dentror de listas
list_num = [x**2 for x in range(100)]

In [2]:
list_num

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801]

In [4]:
#obter uma lista somente com elementos de valores par da 'list_num'
list_par = [x for x in list_num if x % 2 == 0]

In [5]:
list_par

[0,
 4,
 16,
 36,
 64,
 100,
 144,
 196,
 256,
 324,
 400,
 484,
 576,
 676,
 784,
 900,
 1024,
 1156,
 1296,
 1444,
 1600,
 1764,
 1936,
 2116,
 2304,
 2500,
 2704,
 2916,
 3136,
 3364,
 3600,
 3844,
 4096,
 4356,
 4624,
 4900,
 5184,
 5476,
 5776,
 6084,
 6400,
 6724,
 7056,
 7396,
 7744,
 8100,
 8464,
 8836,
 9216,
 9604]

In [6]:
#De uma sequência de caracteres retornar cada caracter
letras = [letra for letra in 'Python']

In [7]:
letras

['P', 'y', 't', 'h', 'o', 'n']

### Dicionários

In [8]:
#Exemplo de lista
salario_list = ['Pedro',1000,'Carlos',750,'Ricardo',2000,'Letícia',2500]

In [9]:
salario_list

['Pedro', 1000, 'Carlos', 750, 'Ricardo', 2000, 'Letícia', 2500]

In [10]:
type(salario_list)

list

In [12]:
#Exemplo de dicionário
salario_dict = {'Pedro':1000,'Carlos':570,'Ricardo':2000,'Letícia':2500}

In [13]:
salario_dict

{'Pedro': 1000, 'Carlos': 570, 'Ricardo': 2000, 'Letícia': 2500}

In [14]:
type(salario_dict)

dict

In [15]:
#Qual é o salário de Pedro?
salario_dict['Pedro']

1000

In [16]:
#Qual é o salário de Letícia?
salario_dict['Letícia']

2500

In [17]:
len(salario_dict)

4

In [18]:
#Adiciona o salário de Rafael
salario_dict['Rafael'] = 1200

In [19]:
salario_dict

{'Pedro': 1000,
 'Carlos': 570,
 'Ricardo': 2000,
 'Letícia': 2500,
 'Rafael': 1200}

In [20]:
len(salario_dict)

5

#### Métodos dos dicionários

In [21]:
#Retorna as chaves do dicionário
salario_dict.keys()

dict_keys(['Pedro', 'Carlos', 'Ricardo', 'Letícia', 'Rafael'])

In [22]:
#Retorna os valores do dicionário
salario_dict.values()

dict_values([1000, 570, 2000, 2500, 1200])

In [23]:
#Para juntas 2 dicionários
#Dicionário 1 contendo os nome e respectivos pesos (Kg)
pesos1 = {'Paulo':57, 'Priscila':65}

In [25]:
#Dicionário 2 contendo os nomes e respectivos pesos (Kg)
pesos2 = {'Débora': 68, 'Jeferson':70}

In [26]:
#Agrupa dicionário peso2 em peso1
pesos1.update(pesos2)

In [27]:
pesos1

{'Paulo': 57, 'Priscila': 65, 'Débora': 68, 'Jeferson': 70}

In [28]:
#Deleta a chave Paulo com seu respectivo valor
del pesos1['Paulo']

In [29]:
pesos1

{'Priscila': 65, 'Débora': 68, 'Jeferson': 70}

In [30]:
#Limpa todo o dicionário
pesos1.clear()

In [31]:
pesos1

{}

In [32]:
#Deleta o dicionário pesos2 - não apenas o conteúdo
#como é feito com o método .clear()
del pesos2

In [33]:
pesos2 #teremos um erro, pois não existe mais a variável na memória

NameError: name 'pesos2' is not defined

In [34]:
#Dicionário misto
dicionario = {'Maria':53,77:'João','Nome':'Silva'}

In [35]:
dicionario

{'Maria': 53, 77: 'João', 'Nome': 'Silva'}

In [36]:
#Acesssando o valor a partir da chave Maria
dicionario['Maria']

53

In [37]:
#Acessando o valor a partir da chave 77
dicionario[77]

'João'

In [38]:
#Acessando o valor a partir da chave Nome
dicionario['Nome']

'Silva'

In [40]:
#Criar dicionário de listas
dic1 = {'chaves1':231,'chaves2':[3,4,5,3],'chaves3':['seg','ter','qua','qui','sex','sab','dom']}

In [41]:
dic1

{'chaves1': 231,
 'chaves2': [3, 4, 5, 3],
 'chaves3': ['seg', 'ter', 'qua', 'qui', 'sex', 'sab', 'dom']}

In [42]:
#Dicionários aninhados
dic2 = {'c1':1,'c2':77,'c3':{'d1':10,'d2':5,'d3':17}}

In [43]:
dic2

{'c1': 1, 'c2': 77, 'c3': {'d1': 10, 'd2': 5, 'd3': 17}}

In [44]:
dic2['c3']

{'d1': 10, 'd2': 5, 'd3': 17}

In [45]:
type(dic2['c3'])

dict

### Tuplas

In [46]:
#Definição de uma tupla sem parênteses
tupla1 = 'a','b','c','d','e'

In [47]:
tupla1

('a', 'b', 'c', 'd', 'e')

In [48]:
type(tupla1)

tuple

In [49]:
#Definição de uma tupla com parêntese
tupla2 = ('a','b','c','d','e')

In [50]:
tupla2

('a', 'b', 'c', 'd', 'e')

In [51]:
type(tupla2)

tuple

In [52]:
#Obs: tuplas são imutáveis
tupla = (11,1.5,154,77,'Maria')

In [53]:
tupla

(11, 1.5, 154, 77, 'Maria')

In [54]:
tupla[2]

154

In [55]:
#não é possível deletar um elemento de uma tupla
del tupla[1]

TypeError: 'tuple' object doesn't support item deletion

In [56]:
#Mas podemos deletar a tupla inteira
del tupla

In [57]:
tupla #mostrará um erro porque a tupla não existe mais na memória

NameError: name 'tupla' is not defined

In [58]:
#Também não é possível adicionar outro item a tupla
tupla = 1,2,3

In [59]:
tupla

(1, 2, 3)

In [60]:
tupla[3] = 4 #exibe um erro porque a tupla é imutável e não aceita adicionar item

TypeError: 'tuple' object does not support item assignment

In [61]:
#Para fazer alterações numa tupla é possível transformá-la numa lista
lis1 = list(tupla)

In [62]:
#Adicionar o valor a lista
lis1.append(4)

In [63]:
#Transformar a lista em tupla
tupla = tuple(lis1)

In [64]:
tupla

(1, 2, 3, 4)

### Vetores e matrizes

In [66]:
import numpy as np #para trabalhar com arrays é necessário usar a biblioteca NumPy

In [67]:
#Criar um vetor
vet1 = np.array([1,2,3,4])

In [68]:
vet1

array([1, 2, 3, 4])

In [69]:
type(vet1)

numpy.ndarray

In [70]:
#Array não aceita tipos diferentes de int, float ou double
vet2 = np.array([1,2,3,'4']) #tentando adicionar str '4'

In [71]:
#Ao fazer isso, o python transforma todos os elementos em strings
vet2

array(['1', '2', '3', '4'], dtype='<U21')

In [72]:
vet2[1]

'2'

In [73]:
type(vet2[1])

numpy.str_

In [74]:
#Por que o python não transformou o '4' em número?
vet3 = np.array([7,8,9,'a'])

In [75]:
#Porque não seria possível transformar 'a' em número
vet3

array(['7', '8', '9', 'a'], dtype='<U21')

In [76]:
type(vet3[0])

numpy.str_

In [79]:
#Matrizes
#Define uma matrix com 2 linhas e 3 colunas
a = np.array([[1,2,3],[3,4,5]])

In [80]:
a2 = np.matrix([[1,2,3],[3,4,5]])

In [81]:
type(a)

numpy.ndarray

In [82]:
type(a2)

numpy.matrix

In [83]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [84]:
a2

matrix([[1, 2, 3],
        [3, 4, 5]])

In [85]:
#Para obter elementos e fatias das matrizes
#Acessar elemento da linha 2 e coluna 3
a[1,2]

5

In [86]:
#Obter todos os elementos da linha 1
a[0,:]

array([1, 2, 3])

In [87]:
#Obter os elementos da coluna 2
a2[:,1]

matrix([[2],
        [4]])

In [88]:
#comportamento de manter o tipo de elementos
b = np.array([[1,2,3],[3,4,'5']])

In [89]:
b

array([['1', '2', '3'],
       ['3', '4', '5']], dtype='<U21')

In [90]:
#O pyhton transformou todos os elementos em string
type(b[0][0])

numpy.str_

In [91]:
#Operações com vetores e matrizes

In [92]:
#Defina o vetor
v = np.array([11,22,33])

In [96]:
a = np.array([[1,2,3],[4,5,6]])

In [97]:
#Defina a matriz
b = np.array([[1,1,1],[2,3,3]])

In [98]:
#Soma o vetor com a matriz
sva = v + a

In [99]:
sva

array([[12, 24, 36],
       [15, 27, 39]])

In [100]:
#O python realiza algumas operação elemento a elemento

In [101]:
#Multiplica o vetor 'v' pela matriz 'a'
va = v*a

In [102]:
va

array([[ 11,  44,  99],
       [ 44, 110, 198]])

In [103]:
#Soma dos elementos das matrizes
c = a+b

In [104]:
c

array([[2, 3, 4],
       [6, 8, 9]])

In [105]:
#Operações com matrizes
d = 2*a+b

In [106]:
d

array([[ 3,  5,  7],
       [10, 13, 15]])

In [107]:
#Multiplica elementos das matrizes
mab = a*b

In [108]:
mab

array([[ 1,  2,  3],
       [ 8, 15, 18]])

In [109]:
#Multplicação matricial
dab = np.dot(a,b) #resulta em erro porque não há concordância entre o número de colunas e linhas das duas matrizes

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [110]:
#Para multiplicação matricial devemos ter
#nº de colunas de 'a' igual nº de linhas de 'b'
dab = np.dot(a,b.T) #b.T -> transposta de 'b' 

In [111]:
dab

array([[ 6, 17],
       [15, 41]])